# Handwritten digits classification using CNN(Exercise) in Google Colab

In [1]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
%matplotlib inline

In [2]:
(X_train, y_train) , (X_test, y_test) = keras.datasets.mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [3]:
X_train.shape

(60000, 28, 28)

In [4]:
y_train.shape

(60000,)

In [5]:
X_train = X_train / 255
X_test = X_test / 255

In [17]:
X_train[:2], X_train.shape

(array([[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],
 
        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]]), (60000, 28, 28))

In [13]:
y_train[:2]

array([5, 0], dtype=uint8)

# Testing the Handwritten dataset on ANN

In [6]:
model_with_ANN=keras.Sequential([
    keras.layers.Flatten(input_shape=(28,28)),
    keras.layers.Dense(100, activation='relu') ,
    keras.layers.Dense(10, activation='sigmoid') 
])

model_with_ANN.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
model_with_ANN.fit(X_train,y_train,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2694 - accuracy: 0.9234
Epoch 2/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1226 - accuracy: 0.9641
Epoch 3/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0855 - accuracy: 0.9741
Epoch 4/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0665 - accuracy: 0.9790
Epoch 5/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0513 - accuracy: 0.9841
Epoch 6/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0409 - accuracy: 0.9875
Epoch 7/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0344 - accuracy: 0.9890
Epoch 8/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0278 - accuracy: 0.9911
Epoch 9/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0217 - accuracy: 0.9936
Epoch 10/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.019

# Testing the dataset on CNN

In [7]:
cnn=keras.Sequential([
    
    #CNN
    keras.layers.Conv2D(30,(3,3), activation='relu', input_shape=(28,28,1)),
    keras.layers.MaxPool2D((2,2)),
    keras.layers.Conv2D(15,(3,3), activation='relu'),
    keras.layers.MaxPool2D((2,2)),
    
    #Dense Layers(Neural Network)
    keras.layers.Flatten(),
    keras.layers.Dense(100, activation='relu'),
    keras.layers.Dense(10, activation='softmax' )
])

cnn.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [8]:
# with tf.device('/CPU:0'):
cnn.fit(X_train,y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 48s 25ms/step - loss: 0.1756 - accuracy: 0.9459
Epoch 2/10
1875/1875 [==============================] - 46s 25ms/step - loss: 0.0574 - accuracy: 0.9820
Epoch 3/10
1875/1875 [==============================] - 46s 24ms/step - loss: 0.0407 - accuracy: 0.9873
Epoch 4/10
1875/1875 [==============================] - 45s 24ms/step - loss: 0.0323 - accuracy: 0.9900
Epoch 5/10
1875/1875 [==============================] - 47s 25ms/step - loss: 0.0253 - accuracy: 0.9918
Epoch 6/10
1875/1875 [==============================] - 44s 24ms/step - loss: 0.0206 - accuracy: 0.9934
Epoch 7/10
1875/1875 [==============================] - 44s 23ms/step - loss: 0.0180 - accuracy: 0.9944
Epoch 8/10
1875/1875 [==============================] - 46s 24ms/step - loss: 0.0136 - accuracy: 0.9956
Epoch 9/10
1875/1875 [==============================] - 45s 24ms/step - loss: 0.0124 - accuracy: 0.9958
Epoch 10/10
1875/1875 [==============================] - 44s 23m

In [19]:
cnn.fit(X_train,y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 48s 26ms/step - loss: 0.0088 - accuracy: 0.9973
Epoch 2/5
1875/1875 [==============================] - 47s 25ms/step - loss: 0.0076 - accuracy: 0.9973
Epoch 3/5
1875/1875 [==============================] - 48s 26ms/step - loss: 0.0079 - accuracy: 0.9976
Epoch 4/5
1875/1875 [==============================] - 46s 25ms/step - loss: 0.0066 - accuracy: 0.9977
Epoch 5/5
1875/1875 [==============================] - 46s 25ms/step - loss: 0.0065 - accuracy: 0.9978


In [20]:
y_train[:5]

array([5, 0, 4, 1, 9], dtype=uint8)

In [21]:
cnn.evaluate(X_test,y_test)

313/313 [==============================] - 3s 10ms/step - loss: 0.0366 - accuracy: 0.9917


[0.03655201569199562, 0.9916999936103821]