# Using Supervised Learning for Embedding of Words.

> This is an old approach and is not that much popular. We are using it to predict wheather the food reviews are positive or negative. Hence, this is a Food Review Classification problem or an NLP problem in general.

In [26]:
import numpy as np
import tensorflow
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [6]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

# '1' means postive review and '0' means negative review
sentiment = np.array([1,1,1,1,1,0,0,0,0,0]) 

## Converting the reviews

> Using One Hot encoding to convert the reviews into feature vectors or one hot encoded vectors because machine can't understand words/strings.

In [10]:
one_hot('nice food',30) # '30' is the vocabulary size, so it will give unique numbers to the words between 1-30.

[13, 3]

In [11]:
VOCAB_SIZE=30

encoded_reviews=[one_hot(review, VOCAB_SIZE) for review in reviews]
encoded_reviews

[[13, 3],
 [5, 1],
 [23, 9],
 [29, 23, 20],
 [9, 11, 21],
 [22, 3],
 [7, 11, 20],
 [22, 15],
 [22, 28],
 [19, 29]]

In [12]:
len(encoded_reviews)

10

In [16]:
np.argmax(encoded_reviews)

/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


3

In [21]:
MAX_LENGTH=np.argmax(encoded_reviews) +1
MAX_LENGTH

/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


4

In [24]:
MAX_LENGTH=np.argmax(encoded_reviews) +1 
padded_reviews= pad_sequences(encoded_reviews,maxlen=MAX_LENGTH, padding='post') # 'post' means towards the end
padded_reviews

/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


array([[13,  3,  0,  0],
       [ 5,  1,  0,  0],
       [23,  9,  0,  0],
       [29, 23, 20,  0],
       [ 9, 11, 21,  0],
       [22,  3,  0,  0],
       [ 7, 11, 20,  0],
       [22, 15,  0,  0],
       [22, 28,  0,  0],
       [19, 29,  0,  0]], dtype=int32)

In [23]:
len(padded_reviews)

10

In [28]:
EMBEDED_VECTOR_SIZE=5

model=Sequential()
model.add(Embedding(VOCAB_SIZE,EMBEDED_VECTOR_SIZE, input_length=MAX_LENGTH, name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid')) # 1 neuron sigmoid activation function

In [29]:
X= padded_reviews
y=sentiment

In [30]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten_1 (Flatten)         (None, 20)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________


In [31]:
model.fit(X,y,epochs=50,verbose=0)

In [32]:
loss, accuracy=model.evaluate(X,y)
accuracy

1/1 [==============================] - 0s 277ms/step - loss: 0.6375 - accuracy: 1.0000


1.0

## Word Embeddings

> The sentiment classification is a fake problem, we are more interested in word embeddings. While solving the sentiment classification problem, we got the word embeddings. Word embeddings are nothing but those parameters in the neural network.

In [34]:
weights=model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [36]:
weights[13]

array([-0.03869608, -0.06790911, -0.02366788, -0.00437879, -0.07389026],
      dtype=float32)

In [37]:
weights[5]

array([-0.07242334, -0.05629948, -0.02245453, -0.07807696, -0.05699418],
      dtype=float32)