In [2]:
import numpy as np

## DataTypes and Attributes

# Numpy's main datatype is ndarray 

In [3]:
a1=np.array([1,2,3])

In [4]:
a1

array([1, 2, 3])

In [5]:
a1.dtype

dtype('int64')

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2=np.array([[1,2.0,3.3],[4,5,6.5]])

a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.shape # (1,3) but numpy represents it as (3,)

(3,)

In [13]:
a1.ndim, a2.ndim, a3.ndim #Number of dimensions

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype,a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [15]:
a1.size #Number of elements in the array

3

In [16]:
type(a1)

numpy.ndarray

In [17]:
import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Numpy Arrays

In [18]:
numpyArray= np.array([1,2,3])
numpyArray

array([1, 2, 3])

In [19]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [23]:
twos=np.ones((2,3),dtype='int8')
twos

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [24]:
twos.dtype

dtype('int8')

In [28]:
evenRange= np.arange(0,11,2) # Not including the stop number.
evenRange

array([ 0,  2,  4,  6,  8, 10])

In [39]:
randomArray=np.random.randint(10,100,size=10)
randomArray

array([76, 19, 62, 60, 51, 32, 20, 10, 84, 78])

In [37]:
randomArray=np.random.randint(90,100,10)
randomArray

array([96, 94, 97, 95, 99, 93, 98, 92, 99, 98])

In [42]:
randomArray=np.random.randint(10,100,size=(3,5))
randomArray

array([[27, 20, 35, 36, 11],
       [29, 72, 94, 70, 96],
       [83, 24, 80, 55, 93]])

In [43]:
randomArray.size

15

In [44]:
randomArray.shape

(3, 5)

In [45]:
# Pseudo Random numbers

In [60]:
np.random.seed(69)
randomNumbers=np.random.randint(10,100)
randomNumbers

64

In [62]:
randomNumbers=np.random.randint(10,100)
randomNumbers

83

## Viewing arrays and Matrics

In [65]:
np.unique(randomArray)

array([11, 20, 24, 27, 29, 35, 36, 55, 70, 72, 80, 83, 93, 94, 96])

In [66]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [67]:
a2[1]

array([4. , 5. , 6.5])

In [68]:
a2[0]

array([1. , 2. , 3.3])

In [69]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [70]:
a4=np.random.randint(10, size=(2,3,4,5))
a4

array([[[[7, 4, 1, 6, 9],
         [8, 1, 6, 0, 8],
         [5, 4, 5, 3, 0],
         [7, 8, 2, 3, 7]],

        [[8, 8, 9, 7, 3],
         [6, 5, 1, 6, 5],
         [7, 0, 0, 3, 2],
         [1, 2, 5, 8, 0]],

        [[9, 2, 1, 3, 7],
         [5, 0, 0, 1, 0],
         [8, 9, 7, 5, 4],
         [9, 9, 9, 2, 7]]],


       [[[1, 5, 5, 3, 4],
         [1, 9, 3, 6, 7],
         [3, 1, 5, 9, 9],
         [4, 0, 5, 0, 3]],

        [[8, 8, 7, 2, 7],
         [0, 9, 1, 0, 7],
         [0, 2, 3, 9, 2],
         [9, 7, 8, 3, 0]],

        [[1, 1, 3, 1, 5],
         [2, 1, 3, 9, 8],
         [8, 6, 8, 5, 3],
         [5, 8, 7, 2, 9]]]])

In [71]:
a4.shape

(2, 3, 4, 5)

In [72]:
a4.ndim

4

In [74]:
a4[:2,:2,:2,:2]

array([[[[7, 4],
         [8, 1]],

        [[8, 8],
         [6, 5]]],


       [[[1, 5],
         [1, 9]],

        [[8, 8],
         [0, 9]]]])

In [80]:
a4[:2,:4,:1,:5]

array([[[[7, 4, 1, 6, 9]],

        [[8, 8, 9, 7, 3]],

        [[9, 2, 1, 3, 7]]],


       [[[1, 5, 5, 3, 4]],

        [[8, 8, 7, 2, 7]],

        [[1, 1, 3, 1, 5]]]])

In [78]:
a4

array([[[[7, 4, 1, 6, 9],
         [8, 1, 6, 0, 8],
         [5, 4, 5, 3, 0],
         [7, 8, 2, 3, 7]],

        [[8, 8, 9, 7, 3],
         [6, 5, 1, 6, 5],
         [7, 0, 0, 3, 2],
         [1, 2, 5, 8, 0]],

        [[9, 2, 1, 3, 7],
         [5, 0, 0, 1, 0],
         [8, 9, 7, 5, 4],
         [9, 9, 9, 2, 7]]],


       [[[1, 5, 5, 3, 4],
         [1, 9, 3, 6, 7],
         [3, 1, 5, 9, 9],
         [4, 0, 5, 0, 3]],

        [[8, 8, 7, 2, 7],
         [0, 9, 1, 0, 7],
         [0, 2, 3, 9, 2],
         [9, 7, 8, 3, 0]],

        [[1, 1, 3, 1, 5],
         [2, 1, 3, 9, 8],
         [8, 6, 8, 5, 3],
         [5, 8, 7, 2, 9]]]])

In [82]:
a4[:, :, :,:1]

array([[[[7],
         [8],
         [5],
         [7]],

        [[8],
         [6],
         [7],
         [1]],

        [[9],
         [5],
         [8],
         [9]]],


       [[[1],
         [1],
         [3],
         [4]],

        [[8],
         [0],
         [0],
         [9]],

        [[1],
         [2],
         [8],
         [5]]]])

## Manipulating and comparing Arrays

In [83]:
a1

array([1, 2, 3])

In [84]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [85]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [89]:
sum=np.ones(3)
sum

array([1., 1., 1.])

In [88]:
a1 + sum

array([2., 3., 4.])

In [90]:
a1 - sum

array([0., 1., 2.])

In [92]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [93]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [94]:
a2.shape

(2, 3)

In [95]:
a3.shape

(2, 3, 3)

In [96]:
a1, a1.shape

(array([1, 2, 3]), (3,))

In [97]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [98]:
a1

array([1, 2, 3])

In [99]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [100]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [107]:
reshapedA3= np.reshape(a3, (3,6))
reshapedA3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [108]:
a2 * reshapedA3

ValueError: operands could not be broadcast together with shapes (2,3) (3,6) 

In [109]:
reshapedA3.shape

(3, 6)

In [110]:
a2.shape

(2, 3)

In [114]:
np.dot(a2, reshapedA3)

array([[ 57.9,  64.2,  70.5,  76.8,  83.1,  89.4],
       [123.5, 139. , 154.5, 170. , 185.5, 201. ]])

In [115]:
np.dot(a2,a3)

array([[[ 32.1,  38.4,  44.7],
        [ 88.8,  95.1, 101.4]],

       [[ 69.5,  85. , 100.5],
        [209. , 224.5, 240. ]]])

In [116]:
a3.shape

(2, 3, 3)

In [ ]:
#8