In [1]:
import numpy as np

## DataTypes and Attributes

# Numpy's main datatype is ndarray 

In [2]:
a1=np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
a1.dtype

dtype('int64')

In [5]:
type(a1)

numpy.ndarray

In [7]:
a2=np.array([[1,2.0,3.3],[4,5,6.5]])

a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1.shape # (1,3) but numpy represents it as (3,)

(3,)

In [14]:
a1.ndim, a2.ndim, a3.ndim #Number of dimensions

(1, 2, 3)

In [18]:
a1.dtype, a2.dtype,a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [19]:
a1.size #Number of elements in the array

3

In [20]:
type(a1)

numpy.ndarray

In [22]:
import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [ ]:
# Completed till 4