# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [8]:
# Create a 1-dimensional NumPy array using np.array()
arr1=np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
arr2=np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr3.shape

(1, 3, 3)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [9]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr1.shape, arr1.size, type(arr1)

((3,), 3, numpy.ndarray)

In [10]:
# Attributes of 2-dimensional array
arr2.shape, arr2.size, type(arr2)

((2, 3), 6, numpy.ndarray)

In [11]:
# Attributes of 3-dimensional array
arr3.shape, arr3.size, type(arr3)

((1, 3, 3), 9, numpy.ndarray)

In [21]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df=pd.DataFrame()
df['1']=arr1
df=pd.concat([arr2,arr3], axis='columns')
df

TypeError: cannot concatenate object of type '<class 'numpy.ndarray'>'; only Series and DataFrame objs are valid

In [25]:
# Create an array of shape (10, 2) with only ones
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
# Create an array of shape (7, 2, 3) of only zeros
zeros=np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [30]:
# Create an array within a range of 0 and 100 with step 3
range=np.arange(0,100,3)
range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [31]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random=np.random.randint(10, size=(7,2))
random

array([[3, 6],
       [0, 1],
       [5, 0],
       [9, 6],
       [2, 2],
       [0, 5],
       [1, 1]])

In [32]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
randomFT=np.random.random((3,5))
randomFT

array([[0.41237283, 0.23070794, 0.48768925, 0.62662629, 0.47411631],
       [0.07343332, 0.06719507, 0.03298614, 0.38341651, 0.80077045],
       [0.36300934, 0.42888798, 0.00349198, 0.09963327, 0.85147526]])

In [35]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
randomS=np.random.randint(10,size=(4,6))
randomS

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [36]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random1=np.random.randint(10,size=(3,7))
random1

# Find the unique numbers in the array you just created


array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6],
       [1, 3, 8, 1, 9, 8, 9]])

In [37]:
# Find the 0'th index of the latest array you created
random1[0][0]

8

In [38]:
# Get the first 2 rows of latest array you created
random1[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [46]:
# Get the first 2 values of the first 2 rows of the latest array
random1[:2:2,:2]

array([[8, 0]])

In [48]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random10=np.random.randint(10, size=(3,5))
randomOnes=np.ones((3,5))

In [51]:
random10

array([[3, 5, 1, 9, 1],
       [9, 3, 7, 6, 8],
       [7, 4, 1, 4, 7]])

In [50]:
# Add the two arrays together
add=random10 + randomOnes
add

array([[ 4.,  6.,  2., 10.,  2.],
       [10.,  4.,  8.,  7.,  9.],
       [ 8.,  5.,  2.,  5.,  8.]])

In [56]:
# Create another array of ones of shape (5, 3)
ones=np.ones((5,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
# Try add the array of ones and the other most recent array together
sum=ones + add.T
sum

array([[ 5., 11.,  9.],
       [ 7.,  5.,  6.],
       [ 3.,  9.,  3.],
       [11.,  8.,  6.],
       [ 3., 10.,  9.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [ ]:
# Create another array of ones of shape (3, 5)
another=np.random.randint(10, size=(3,5))
another

array([[4, 2, 7, 5, 2],
       [0, 2, 4, 2, 0],
       [4, 9, 6, 6, 8]])

In [68]:
# Subtract the new array of ones from the other most recent array
sub=ones-another.T
sub

array([[-3.,  1., -3.],
       [-1., -1., -8.],
       [-6., -3., -5.],
       [-4., -1., -5.],
       [-1.,  1., -7.]])

In [70]:
# Multiply the ones array with the latest array
mul=another * sub.T

In [72]:
# Take the latest array to the power of 2 using '**'

power= mul ** another
power

array([[ 2.07360000e+04,  4.00000000e+00, -2.30539333e+11,
        -3.20000000e+06,  4.00000000e+00],
       [ 1.00000000e+00,  4.00000000e+00,  2.07360000e+04,
         4.00000000e+00,  1.00000000e+00],
       [ 2.07360000e+04, -5.19986978e+16,  7.29000000e+08,
         7.29000000e+08,  9.67173116e+13]])

In [74]:
# Do the same thing with np.square()
np.square(mul)

array([[1.440e+02, 4.000e+00, 1.764e+03, 4.000e+02, 4.000e+00],
       [0.000e+00, 4.000e+00, 1.440e+02, 4.000e+00, 0.000e+00],
       [1.440e+02, 5.184e+03, 9.000e+02, 9.000e+02, 3.136e+03]])

In [75]:
# Find the mean of the latest array using np.mean()
np.mean(mul)

-19.6

In [77]:
# Find the maximum of the latest array using np.max()
np.max(another)

9

In [79]:
# Find the minimum of the latest array using np.min()
np.min(mul)

-72.0

In [81]:
# Find the standard deviation of the latest array
np.std(mul)

21.555509736491967

In [82]:
# Find the variance of the latest array
np.var(mul)

464.64

In [84]:
mul

array([[-12.,  -2., -42., -20.,  -2.],
       [  0.,  -2., -12.,  -2.,   0.],
       [-12., -72., -30., -30., -56.]])

In [85]:
mul.shape

(3, 5)

In [83]:
# Reshape the latest array to (3, 5, 1)
np.reshape(mul,(3,5,1))

array([[[-12.],
        [ -2.],
        [-42.],
        [-20.],
        [ -2.]],

       [[  0.],
        [ -2.],
        [-12.],
        [ -2.],
        [  0.]],

       [[-12.],
        [-72.],
        [-30.],
        [-30.],
        [-56.]]])

In [86]:
# Transpose the latest array
mul.T

array([[-12.,   0., -12.],
       [ -2.,  -2., -72.],
       [-42., -12., -30.],
       [-20.,  -2., -30.],
       [ -2.,   0., -56.]])

What does the transpose do?

In [88]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
one=np.ones((3,3))
two=np.ones((3,2))

In [89]:
# Perform a dot product on the two newest arrays you created
np.dot(one,two)

array([[3., 3.],
       [3., 3.],
       [3., 3.]])

In [93]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
one=np.random.randint(10,size=(4,3))
two=np.random.randint(10,size=(4,3))

In [97]:
# Perform a dot product on the two newest arrays you created
np.dot(one,two)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [96]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(one,two.T)

array([[ 27,  45,  18,  48],
       [ 86, 102,  68,  96],
       [ 58,  75,  60,  64],
       [ 89,  78,  46,  80]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [98]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
one=np.random.randint(10,size=(4,3))
two=np.random.randint(10,size=(4,3))

In [99]:
# Compare the two arrays with '>'
one > two

array([[False,  True, False],
       [ True,  True,  True],
       [False,  True, False],
       [ True,  True,  True]])

What happens when you compare the arrays with `>`?

In [100]:
# Compare the two arrays with '>='
one >= two

array([[False,  True, False],
       [ True,  True,  True],
       [False,  True, False],
       [ True,  True,  True]])

In [101]:
# Find which elements of the first array are greater than 7
one > 7

array([[False,  True, False],
       [False, False, False],
       [ True, False, False],
       [False,  True, False]])

In [102]:
# Which parts of each array are equal? (try using '==')
one == two

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [103]:
# Sort one of the arrays you just created in ascending order
np.sort(one)

array([[2, 3, 8],
       [5, 6, 7],
       [0, 4, 8],
       [2, 7, 9]])

In [105]:
# Sort the indexes of one of the arrays you just created
np.argsort(one)

array([[2, 0, 1],
       [1, 0, 2],
       [2, 1, 0],
       [0, 2, 1]])

In [107]:
one

array([[3, 8, 2],
       [6, 5, 7],
       [8, 4, 0],
       [2, 9, 7]])

In [106]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(one)

10

In [109]:
one[:10]

array([[3, 8, 2],
       [6, 5, 7],
       [8, 4, 0],
       [2, 9, 7]])

In [110]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(one)

8

In [112]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(one, axis=1)

array([1, 2, 0, 1])

In [113]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(one, axis=0)

array([2, 3, 1])

In [114]:
# Create an array of normally distributed random numbers
np.random.randn(10)

array([-0.44176602, -0.08416509,  1.23701607, -1.42647888,  0.33802266,
        1.9745712 ,  1.96503476, -1.93991122, -0.76262696,  0.16865939])

In [115]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.